on:
  pull_request:
    types: closed

jobs:
  check_pr_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check PR Merged
        id: check_pr_merged
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prUrl = c.html_url ?? context.payload.pull_request._links.html.href;
            const mergedBy = github.head_ref;
            const baseBranch = context.payload.pull_request.base.ref;
            core.debug(JSON.stringify(context.payload.pull_request));
            core.debug(JSON.stringify(github));
            core.setOutput('pullRequestLink', JSON.stringify(prUrl));
            core.setOutput('mergedBy', JSON.stringify(mergedBy));
            core.setOutput('baseBranch', JSON.stringify(baseBranch));
      - name: Delete Branch
        if: ${{ github.ref_name }} !== ${{ steps.check_pr_merged.outputs.mergerdBy }}
        run: |
          git branch -d ${{ steps.check_pr_merged.outputs.mergerdBy }}
          git push origin --delete ${{ steps.check_pr_merged.outputs.mergerdBy }}
