on:
  pull_request:
    types: closed

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get branch names
        id: get_branch_name
        run: |
          const baseBranch = ${{ github.event.pull_request.base.ref }}
          const headBranch = ${{ github.event.pull_request.head.ref }}
          core.setOutput('baseBranch', JSON.strigify(baseBranch));
          core.setOutput('headBranch', JSON.stringify(headBranch));
      - name: Delete Branch
        if: ${{ steps.get_branch_name.outputs.baseBranch }}  !== ${{ steps.get_branch_name.outputs.headBranch }}
        run: |
          git checkout ${{ steps.get_branch_name.outputs.baseBranch }}
          git branch -d ${{ steps.check_pr_merged.outputs.headBranch }}
          git push origin --delete ${{ steps.check_pr_merged.outputs.headBranch }}
