name: Merge Branches

on:
  pull_request:
    types: [closed]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get branch names
        id: get_branch_name
        run: |
          baseBranch=${{ github.event.pull_request.base.ref }}
          headBranch=${{ github.event.pull_request.head.ref }}
          echo "::set-output name=baseBranch::${baseBranch}"
          echo "::set-output name=headBranch::${headBranch}"
      - name: Delete Branch
        if: ${{ steps.get_branch_name.outputs.baseBranch }} != ${{ steps.get_branch_name.outputs.headBranch }}
        run: |
          git checkout ${{ steps.get_branch_name.outputs.baseBranch }}
          git branch -d ${{ steps.get_branch_name.outputs.headBranch }}
          git push origin --delete ${{ steps.get_branch_name.outputs.headBranch }}
