on:
  pull_request:
    types: closed

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get branch names
        id: get_branch_name
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}ㅋ
          script: |
            const baseBranch = github.event.pull_request.base.ref;
            const headBranch = github.event.pull_request.head.ref;
            core.setOutput('baseBranch', JSON.stringify(baseBranch));
            core.setOutput('headBranch', JSON.stringify(headBranch));

      - name: Delete Branch
        if: ${{ steps.get_branch_name.outputs.baseBranch }} !== ${{ steps.get_branch_name.outputs.headBranch }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}ㅋ
          script: |
            git checkout ${{ steps.get_branch_name.outputs.baseBranch }}
            git branch -d ${{ steps.get_branch_name.outputs.headBranch }}
            git push origin --delete ${{ steps.get_branch_name.outputs.headBranch }}
