on:
  pull_request:
    types: closed

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get branch names
        run: |
          echo "Base branch: ${{ github.event.pull_request.base.ref }}"
          echo "Head branch: ${{ github.event.pull_request.head.ref }}"
      - name: Delete Branch
        if: ${{ github.ref_name }} !== ${{ steps.check_pr_merged.outputs.mergerdBy }}
        run: |
          git branch -d ${{ steps.check_pr_merged.outputs.mergerdBy }}
          git push origin --delete ${{ steps.check_pr_merged.outputs.mergerdBy }}
